module.exports = {
    AbstractTTS: require("./src/node/abstract-tts"),
    Cursor: require('./src/node/cursor'),
    Definitions: require('./src/node/definitions'),
    Polly: require("./src/node/polly"),
    PoParser: require('./src/node/po-parser'),
    ScvRest: require('./src/node/scv-rest'),
    SectionParser: require('./src/node/section-parser'),
    Section: require('./src/node/section'),
    GuidStore: require("./src/node/guid-store"),
    SuttaCentralApi: require('./src/node/sutta-central-api'),
    SuttaCentralId: require("./src/node/sutta-central-id"),
    SuttaFactory: require("./src/node/sutta-factory"),
    SuttaSearcher: require('./src/node/sutta-searcher'),
    SuttaStore: require('./src/node/sutta-store'),
    Sutta: require("./src/node/sutta"),
    Voice: require('./src/node/voice'),
    Watson: require("./src/node/watson"),
    Words: require('./src/node/words'),

};
