module.exports = {
    AbstractTTS: require("./src/node/abstract-tts"),
    AudioUrls: require("./src/node/audio-urls"),
    ContentUpdater: require('./src/node/content-updater'),
    Definitions: require('./src/node/definitions'),
    HumanTts: require("./src/node/human-tts"),
    MdAria: require("./src/node/md-aria"),
    Polly: require("./src/node/polly"),
    ScvRest: require('./src/node/scv-rest'),
    SectionParser: require('./src/node/section-parser'),
    Section: require('./src/node/section'),
    GuidStore: require("./src/node/guid-store"),
    Playlist: require('./src/node/playlist'),
    SCAudio: require('./src/node/sc-audio'),
    SoundStore: require('./src/node/sound-store'),
    SuttaCentralApi: require('./src/node/sutta-central-api'),
    SuttaCentralId: require("./src/node/sutta-central-id"),
    SuttaFactory: require("./src/node/sutta-factory"),
    SuttaDuration: require("./src/node/sutta-duration"),
    SuttaStore: require('./src/node/sutta-store'),
    Sutta: require("./src/node/sutta"),
    S3Bucket: require('./src/node/s3-bucket'),
    Task: require('./src/node/task'),
    Voice: require('./src/node/voice'),
    VoiceFactory: require('./src/node/voice-factory'),
    VsmStore: require('./src/node/vsm-store'),
    Watson: require("./src/node/watson"),
    Words: require('./src/node/words'),

};
