#!/bin/bash
DIR=`dirname $0`
SCRIPT=`basename $0 | tr abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUVWXYZ`
echo -e "$SCRIPT\t: BEGIN `date`"

npm install --save scv-bilara@latest
git status | grep 'nothing to commit' > /dev/null; RC=$?
if [ "$RC" == "0" ]; then
  echo -e "BUILD\t: nothing to commit"
else
  echo -e "BUILD\t: Updating git..."
  git status
  SCV_VER=`json version < node_modules/scv-bilara/package.json`
  MSG="build with scv-bilara v$SCV_VER"
  echo -e "BUILD\t: $MSG"
  git commit -am "$MSG"
  npm version patch
  VERSION=`json version < package.json`
  git reset --soft HEAD~1
  git commit --amend -m "v$VERSION build"
  git push
fi

echo -e "$SCRIPT\t: END `date`"
