#!/bin/bash

echo -e "UPDATE\t: $0 START `date`"

sudo apt-get update

REBOOT=0
OPTIND=1
while getopts "r" opt; do
    case "$opt" in
    r)  REBOOT=y
        ;;
    esac
done
shift $((OPTIND-1))
[ "$1" = "--" ] && shift

if [ "$1" == "test" ]; then
    echo -e "UPDATE\t: UPDATE TEST COMPLETED"
    exit 0;
fi

if [ "$REBOOT" == "0" ]; then
    while true; do
        echo -e "UPDATE\t: SC-Voice update requires a reboot"
        read -p "UPDATE  : Reboot after update? [y,n]:" REBOOT
        case $REBOOT in
            [y]* ) echo -e "UPDATE\t: (will reboot after update)"; break;;
            [n]* ) break;;
               * ) echo "        : Please enter 'y' or 'n'";;
        esac
    done
fi

echo -e "UPDATE\t: Installing dependencies..."
npm install
sync

echo -e "UPDATE\t: Building web server..."
if [ -e dist ]; then
    rm -rf dist
fi
npm run build
sync

echo -e "UPDATE\t: Upating offline content..."
if [ -e local/sc ]; then
    if [ -e local/sc/.git ]; then
        echo -e "INIT\t: SuttaCentral/translation folder local/sc exists (OK)"
    else
        echo -e "INIT\t: removing legacy SuttaCentral/translation folder "
        rm -rf local/sc
    fi
fi
if [ -e local/sc ]; then
    echo -e "INIT\t: updating SuttaCentral translation content..."
    pushd local/sc
    git pull
    popd
else 
    pushd local
    echo -e "INIT\t: initializing SuttaCentral translation content..."
    git clone https://github.com/suttacentral/translation sc
    popd
fi

if [ -e local/suttas/mn ]; then
    echo -e "INIT\t: updating scv-suttas..."
    pushd local/suttas
    git pull
    popd
else
    pushd local
    rm -rf suttas
    echo -e "INIT\t: installing scv-suttas..."
    git clone https://github.com/sc-voice/scv-suttas suttas
    popd
fi

if [ "$REBOOT" == "y" ]; then
    sudo shutdown -r now
fi

echo -e "UPDATE\t: $0 END `date`"
